from django.db import models
from taggit.managers import TaggableManager

# Create your models here.

class Idea(models.Model):
   
    author_token = models.CharField(max_length=255)


    #id, the primary key is auto-generated by Django
    
    #TextInput
    title = models.CharField(max_length=255)
    #TextInput
    destination = models.CharField(max_length=255)
    #TextArea
    description = models.TextField()
    #tags in the form of string list
    tags = TaggableManager()

    #start and end dates
    start_date = models.DateField("start date")
    
    end_date = models.DateField("end date")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self) -> str:
        return str(self.id) + ": " + self.title
