# Generated by Django 4.0.5 on 2023-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_travel_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='author_token',
            field=models.CharField(default='superuser', max_length=255),
            preserve_default=False,
        ),
    ]
