# Generated by Django 4.0.5 on 2023-08-09 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_travel_ideas', '0002_idea_author_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
